# Generated by Django 3.2.20 on 2023-09-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time_start', models.TimeField(verbose_name='Start time')),
                ('time_end', models.TimeField(verbose_name='End time')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber', to='salon.barber')),
            ],
        ),
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(related_name='services', to='salon.Service'),
        ),
    ]
