# Generated by Django 3.2.20 on 2023-09-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name': 'Working Hours', 'verbose_name_plural': 'Working Hours'},
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='date',
        ),
        migrations.AddField(
            model_name='workinghours',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
    ]
